<a href="https://colab.research.google.com/github/avijeet25/colab_files/blob/master/MiniMax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import chess
#import sunfish
import math
import random
import sys



def minimaxRoot(depth, board,isMaximizing):
    possibleMoves = board.legal_moves
    bestMove = -9999
    secondBest = -9999
    thirdBest = -9999
    bestMoveFinal = None
    for x in possibleMoves:
        move = chess.Move.from_uci(str(x))
        board.push(move)
        value = max(bestMove, minimax(depth - 1, board, not isMaximizing))
        board.pop()
        if( value > bestMove):
            print("Best score: " ,str(bestMove))
            print("Best move: ",str(bestMoveFinal))
            print("Second best: ", str(secondBest))
            thirdBest = secondBest
            secondBest = bestMove
            bestMove = value
            bestMoveFinal = move
    return bestMoveFinal

def minimax(depth, board, is_maximizing):
    if(depth == 0):
        return -evaluation(board)
    possibleMoves = board.legal_moves
    if(is_maximizing):
        bestMove = -9999
        for x in possibleMoves:
            move = chess.Move.from_uci(str(x))
            board.push(move)
            bestMove = max(bestMove,minimax(depth - 1, board, not is_maximizing))
            board.pop()
        return bestMove
    else:
        bestMove = 9999
        for x in possibleMoves:
            move = chess.Move.from_uci(str(x))
            board.push(move)
            bestMove = min(bestMove, minimax(depth - 1, board, not is_maximizing))
            board.pop()
        return bestMove


#def calculateMove(board):
#    possible_moves = board.legal_moves
#    if(len(possible_moves) == 0):
#        print("No more possible moves...Game Over")
#        sys.exit()
#    bestMove = None
#    bestValue = -9999
#    n = 0
#    for x in possible_moves:
#        move = chess.Move.from_uci(str(x))
#        board.push(move)
#        boardValue = -evaluation(board)
#        board.pop()
#        if(boardValue > bestValue):
#            bestValue = boardValue
#            bestMove = move
#
#    return bestMove

def evaluation(board):
    i = 0
    evaluation = 0
    x = True
    try:
        x = bool(board.piece_at(i).color)
    except AttributeError as e:
        x = x
    while i < 63:
        i += 1
        evaluation = evaluation + (getPieceValue(str(board.piece_at(i))) if x else -getPieceValue(str(board.piece_at(i))))
    return evaluation


def getPieceValue(piece):
    if(piece == None):
        return 0
    value = 0
    if piece == "P" or piece == "p":
        value = 10
    if piece == "N" or piece == "n":
        value = 30
    if piece == "B" or piece == "b":
        value = 30
    if piece == "R" or piece == "r":
        value = 50
    if piece == "Q" or piece == "q":
        value = 90
    if piece == 'K' or piece == 'k':
        value = 900
    #value = value if (board.piece_at(place)).color else -value
    return value

def main():
    board = chess.Board()
    n = 0
    print(board)
    while n < 100:
        if n%2 == 0:
            move = input("Enter move: ")
            move = chess.Move.from_uci(str(move))
            board.push(move)
        else:
            print("Computers Turn:")
            move = minimaxRoot(4,board,True)
            move = chess.Move.from_uci(str(move))
            board.push(move)
        print(board)
        n += 1





if __name__ == "__main__":
    main()

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
Enter move: p 1 1


ValueError: ignored

In [16]:
# Tic-Tac-Toe Program using 
# random number in Python 

# importing all necessary libraries 
import numpy as np 
import random 
from time import sleep 

# Creates an empty board 
def create_board(): 
	return(np.array([[0, 0, 0], 
					[0, 0, 0], 
					[0, 0, 0]])) 

# Check for empty places on board 
def possibilities(board): 
	l = [] 
	
	for i in range(len(board)): 
		for j in range(len(board)): 
			
			if board[i][j] == 0: 
				l.append((i, j)) 
	return(l) 

# Select a random place for the player 
def random_place(board, player): 
	selection = possibilities(board) 
	current_loc = random.choice(selection) 
	board[current_loc] = player 
	return(board) 

# Checks whether the player has three 
# of their marks in a horizontal row 
def row_win(board, player): 
	for x in range(len(board)): 
		win = True
		
		for y in range(len(board)): 
			if board[x, y] != player: 
				win = False
				continue
				
		if win == True: 
			return(win) 
	return(win) 

# Checks whether the player has three 
# of their marks in a vertical row 
def col_win(board, player): 
	for x in range(len(board)): 
		win = True
		
		for y in range(len(board)): 
			if board[y][x] != player: 
				win = False
				continue
				
		if win == True: 
			return(win) 
	return(win) 

# Checks whether the player has three 
# of their marks in a diagonal row 
def diag_win(board, player): 
	win = True
	y = 0
	for x in range(len(board)): 
		if board[x, x] != player: 
			win = False
	if win: 
		return win 
	win = True
	if win: 
		for x in range(len(board)): 
			y = len(board) - 1 - x 
			if board[x, y] != player: 
				win = False
	return win 

# Evaluates whether there is 
# a winner or a tie 
def evaluate(board): 
	winner = 0
	
	for player in [1, 2]: 
		if (row_win(board, player) or
			col_win(board,player) or
			diag_win(board,player)): 
				
			winner = player 
			
	if np.all(board != 0) and winner == 0: 
		winner = -1
	return winner 

# Main function to start the game 
def play_game(): 
	board, winner, counter = create_board(), 0, 1
	print(board) 
	sleep(2) 
	
	while winner == 0: 
		for player in [1, 2]: 
			board = random_place(board, player) 
			print("Board after " + str(counter) + " move") 
			print(board) 
			sleep(2) 
			counter += 1
			winner = evaluate(board) 
			if winner != 0: 
				break
	return(winner) 

# Driver Code 
print("Winner is: " + str(play_game())) 


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 1 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[2 1 0]
 [0 0 0]
 [0 0 0]]
Board after 3 move
[[2 1 0]
 [0 0 0]
 [0 0 1]]
Board after 4 move
[[2 1 0]
 [0 2 0]
 [0 0 1]]
Board after 5 move
[[2 1 1]
 [0 2 0]
 [0 0 1]]
Board after 6 move
[[2 1 1]
 [0 2 0]
 [0 2 1]]
Board after 7 move
[[2 1 1]
 [0 2 0]
 [1 2 1]]
Board after 8 move
[[2 1 1]
 [2 2 0]
 [1 2 1]]
Board after 9 move
[[2 1 1]
 [2 2 1]
 [1 2 1]]
Winner is: 1
